public/symbols/
 ├─ symbol-cashlab.png
 ├─ symbol-puke.png
 ├─ symbol-slime.png
 ├─ symbol-sneeze.png
 ├─ symbol-tp.png
 ├─ symbol-pill.png
 ├─ symbol-germ.png
 ├─ symbol-beaker.png
 ├─ symbol-vomit.png
 ├─ symbol-toxic.png
 ├─ symbol-barrel.png
 ├─ symbol-warn.png
 ├─ symbol-rich.png
 ├─ symbol-wild.png
 ├─ symbol-scatter.png
 ├─ symbol-bonus.png
 ├─ symbol-hazard.png
 └─ symbol-jackpot.png
